### ISSUE TITLE
muse-tech-central

### ISSUE THREAD

**Issue by smoore4moma** [MuseCompNet/muse-tech-central#17]
just noticed that mcn.edu has redesigned their web site and the github repo is no longer linked from there.  they talk about "community" but i'm not seeing it.  in fact i've always felt that there was not much computer in museum computer network and that the github repo was at least where serious geeks were represented. what's going on?

**Comment by kjaebker** [comment]
Steve,

I helped with the site redesign and this was an oversight and not something intentional. I will talk with the admins and figure out where we can get it added back in. 

As a board member we are always looking for more ways to embrace the community. So I would be happy to talk about ideas you might have to make MCN better. 

Kyle

**Comment by smoore4moma** [comment]
Thanks for the response Kyle. I'm glad to know it was not intentional.

I sent an email today about mcn.edu not being in the top 300 Google search
results (terms: "museum computer network").  I actually submitted it to
Google for MCN.  But there is a more comprehensive way by doing the steps
here:

https://www.google.com/webmasters/tools/home?hl=en

Steve

**Comment by mialondon** [comment]
Hi Steve,

perhaps you can help - the MCN front page has '<meta name='robots' content='noindex,follow' />', which means it's not visible in the Internet Archive or search engines. Can you help get that fixed?

Cheers, Mia

**Comment by kjaebker** [comment]
@mialondon what exactly are you referencing here? I can fix it but I'm not sure what you are asking to fix.

Thanks,

Kyle

**Comment by mialondon** [comment]
@kjaebker ah, the line of code I posted was swallowed. Look for: meta name='robots' content='noindex,follow'

**Comment by robl** [comment]
Ah, the typical legacy bit of "suppress until launch" meta. :)

Rob

**Comment by kjaebker** [comment]
ah, ok I think this is fixed. Can you verify for me? I also added the sitemap plugin to help with indexing and submitted it to all relevant search engines.

**Comment by kjaebker** [comment]
ok, its not fixed... hang on

**Comment by robl** [comment]
I'm now seeing (angle brackets deleted below):

  meta name="robots" content="noindex,follow"

...in which "noindex" would want to become "index" like so:

  meta name="robots" content="index,follow"

Rob

**Comment by smoore4moma** [comment]
Follow up from my post here 24 days ago...  Google search for "museum computer network" now has www.mcn.edu as top response.  Kyle, can you reach out to me offline at steven_moore and moma.org.  I have a question about a vendor you use at IMA.  Thanks.

**Comment by kjaebker** [comment]
ok, I finally found the right checkbox to get rid of that. Thanks for the help everyone
